name: raw_cli
description: A sample command-line application.
version: 1.0.0

repository:  https://github.com/raunak-dows17/raunak_cli_flutter.git

environment:
  sdk: ^3.7.1

dependencies:
   path: ^1.9.1
   args: ^2.7.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.26.2
